lib: [
  "_build/install/default/lib/wassail/META"
  "_build/install/default/lib/wassail/analysis/analysis_helpers.ml" {"analysis/analysis_helpers.ml"}
  "_build/install/default/lib/wassail/analysis/call_graph/call_graph.ml" {"analysis/call_graph/call_graph.ml"}
  "_build/install/default/lib/wassail/analysis/instruction_counter/instruction_counter.ml" {"analysis/instruction_counter/instruction_counter.ml"}
  "_build/install/default/lib/wassail/analysis/inter.ml" {"analysis/inter.ml"}
  "_build/install/default/lib/wassail/analysis/intra.ml" {"analysis/intra.ml"}
  "_build/install/default/lib/wassail/analysis/rule_parser/rule_parser.ml" {"analysis/rule_parser/rule_parser.ml"}
  "_build/install/default/lib/wassail/analysis/sizes/sizes.ml" {"analysis/sizes/sizes.ml"}
  "_build/install/default/lib/wassail/analysis/slice/control_deps.ml" {"analysis/slice/control_deps.ml"}
  "_build/install/default/lib/wassail/analysis/slice/dominance.ml" {"analysis/slice/dominance.ml"}
  "_build/install/default/lib/wassail/analysis/slice/memory_deps.ml" {"analysis/slice/memory_deps.ml"}
  "_build/install/default/lib/wassail/analysis/slice/slicing.ml" {"analysis/slice/slicing.ml"}
  "_build/install/default/lib/wassail/analysis/slice/use_def.ml" {"analysis/slice/use_def.ml"}
  "_build/install/default/lib/wassail/analysis/spec/spec.ml" {"analysis/spec/spec.ml"}
  "_build/install/default/lib/wassail/analysis/spec/spec_analysis.ml" {"analysis/spec/spec_analysis.ml"}
  "_build/install/default/lib/wassail/analysis/spec/spec_inference.ml" {"analysis/spec/spec_inference.ml"}
  "_build/install/default/lib/wassail/analysis/spec/var.ml" {"analysis/spec/var.ml"}
  "_build/install/default/lib/wassail/analysis/taint/taint.ml" {"analysis/taint/taint.ml"}
  "_build/install/default/lib/wassail/analysis/taint/taint_domain.ml" {"analysis/taint/taint_domain.ml"}
  "_build/install/default/lib/wassail/analysis/taint/taint_options.ml" {"analysis/taint/taint_options.ml"}
  "_build/install/default/lib/wassail/analysis/taint/taint_summary.ml" {"analysis/taint/taint_summary.ml"}
  "_build/install/default/lib/wassail/analysis/taint/taint_transfer.ml" {"analysis/taint/taint_transfer.ml"}
  "_build/install/default/lib/wassail/analysis/taintcall/taintcall.ml" {"analysis/taintcall/taintcall.ml"}
  "_build/install/default/lib/wassail/analysis/taintcall/taintcall_domain.ml" {"analysis/taintcall/taintcall_domain.ml"}
  "_build/install/default/lib/wassail/analysis/taintcall/taintcall_transfer.ml" {"analysis/taintcall/taintcall_transfer.ml"}
  "_build/install/default/lib/wassail/analysis/transfer.ml" {"analysis/transfer.ml"}
  "_build/install/default/lib/wassail/analysis/var_prop/var_prop.ml" {"analysis/var_prop/var_prop.ml"}
  "_build/install/default/lib/wassail/cfg/basic_block.ml" {"cfg/basic_block.ml"}
  "_build/install/default/lib/wassail/cfg/cfg.ml" {"cfg/cfg.ml"}
  "_build/install/default/lib/wassail/cfg/cfg_builder.ml" {"cfg/cfg_builder.ml"}
  "_build/install/default/lib/wassail/cfg/codegen.ml" {"cfg/codegen.ml"}
  "_build/install/default/lib/wassail/cfg/lexical_successor_tree.ml" {"cfg/lexical_successor_tree.ml"}
  "_build/install/default/lib/wassail/dune-package"
  "_build/install/default/lib/wassail/helpers.ml"
  "_build/install/default/lib/wassail/log.ml"
  "_build/install/default/lib/wassail/opam"
  "_build/install/default/lib/wassail/test.ml"
  "_build/install/default/lib/wassail/unsupported.ml"
  "_build/install/default/lib/wassail/util/tree.ml" {"util/tree.ml"}
  "_build/install/default/lib/wassail/wasm/binop.ml" {"wasm/binop.ml"}
  "_build/install/default/lib/wassail/wasm/convertop.ml" {"wasm/convertop.ml"}
  "_build/install/default/lib/wassail/wasm/data_segment.ml" {"wasm/data_segment.ml"}
  "_build/install/default/lib/wassail/wasm/elem_segment.ml" {"wasm/elem_segment.ml"}
  "_build/install/default/lib/wassail/wasm/export.ml" {"wasm/export.ml"}
  "_build/install/default/lib/wassail/wasm/func.ml" {"wasm/func.ml"}
  "_build/install/default/lib/wassail/wasm/func_inst.ml" {"wasm/func_inst.ml"}
  "_build/install/default/lib/wassail/wasm/global.ml" {"wasm/global.ml"}
  "_build/install/default/lib/wassail/wasm/import.ml" {"wasm/import.ml"}
  "_build/install/default/lib/wassail/wasm/instr.ml" {"wasm/instr.ml"}
  "_build/install/default/lib/wassail/wasm/limits.ml" {"wasm/limits.ml"}
  "_build/install/default/lib/wassail/wasm/memory.ml" {"wasm/memory.ml"}
  "_build/install/default/lib/wassail/wasm/memory_inst.ml" {"wasm/memory_inst.ml"}
  "_build/install/default/lib/wassail/wasm/memoryop.ml" {"wasm/memoryop.ml"}
  "_build/install/default/lib/wassail/wasm/module_inst.ml" {"wasm/module_inst.ml"}
  "_build/install/default/lib/wassail/wasm/prim_value.ml" {"wasm/prim_value.ml"}
  "_build/install/default/lib/wassail/wasm/ref_type.ml" {"wasm/ref_type.ml"}
  "_build/install/default/lib/wassail/wasm/relop.ml" {"wasm/relop.ml"}
  "_build/install/default/lib/wassail/wasm/segment.ml" {"wasm/segment.ml"}
  "_build/install/default/lib/wassail/wasm/segment_mode.ml" {"wasm/segment_mode.ml"}
  "_build/install/default/lib/wassail/wasm/table.ml" {"wasm/table.ml"}
  "_build/install/default/lib/wassail/wasm/table_inst.ml" {"wasm/table_inst.ml"}
  "_build/install/default/lib/wassail/wasm/testop.ml" {"wasm/testop.ml"}
  "_build/install/default/lib/wassail/wasm/type.ml" {"wasm/type.ml"}
  "_build/install/default/lib/wassail/wasm/unop.ml" {"wasm/unop.ml"}
  "_build/install/default/lib/wassail/wasm/wasm_module.ml" {"wasm/wasm_module.ml"}
  "_build/install/default/lib/wassail/wasm_helpers.ml"
  "_build/install/default/lib/wassail/wassail.a"
  "_build/install/default/lib/wassail/wassail.cma"
  "_build/install/default/lib/wassail/wassail.cmi"
  "_build/install/default/lib/wassail/wassail.cmt"
  "_build/install/default/lib/wassail/wassail.cmx"
  "_build/install/default/lib/wassail/wassail.cmxa"
  "_build/install/default/lib/wassail/wassail.ml"
  "_build/install/default/lib/wassail/wassail__.cmi"
  "_build/install/default/lib/wassail/wassail__.cmt"
  "_build/install/default/lib/wassail/wassail__.cmx"
  "_build/install/default/lib/wassail/wassail__.ml"
  "_build/install/default/lib/wassail/wassail__Analysis_helpers.cmi"
  "_build/install/default/lib/wassail/wassail__Analysis_helpers.cmt"
  "_build/install/default/lib/wassail/wassail__Analysis_helpers.cmx"
  "_build/install/default/lib/wassail/wassail__Basic_block.cmi"
  "_build/install/default/lib/wassail/wassail__Basic_block.cmt"
  "_build/install/default/lib/wassail/wassail__Basic_block.cmx"
  "_build/install/default/lib/wassail/wassail__Binop.cmi"
  "_build/install/default/lib/wassail/wassail__Binop.cmt"
  "_build/install/default/lib/wassail/wassail__Binop.cmx"
  "_build/install/default/lib/wassail/wassail__Call_graph.cmi"
  "_build/install/default/lib/wassail/wassail__Call_graph.cmt"
  "_build/install/default/lib/wassail/wassail__Call_graph.cmx"
  "_build/install/default/lib/wassail/wassail__Cfg.cmi"
  "_build/install/default/lib/wassail/wassail__Cfg.cmt"
  "_build/install/default/lib/wassail/wassail__Cfg.cmx"
  "_build/install/default/lib/wassail/wassail__Cfg_builder.cmi"
  "_build/install/default/lib/wassail/wassail__Cfg_builder.cmt"
  "_build/install/default/lib/wassail/wassail__Cfg_builder.cmx"
  "_build/install/default/lib/wassail/wassail__Codegen.cmi"
  "_build/install/default/lib/wassail/wassail__Codegen.cmt"
  "_build/install/default/lib/wassail/wassail__Codegen.cmx"
  "_build/install/default/lib/wassail/wassail__Control_deps.cmi"
  "_build/install/default/lib/wassail/wassail__Control_deps.cmt"
  "_build/install/default/lib/wassail/wassail__Control_deps.cmx"
  "_build/install/default/lib/wassail/wassail__Convertop.cmi"
  "_build/install/default/lib/wassail/wassail__Convertop.cmt"
  "_build/install/default/lib/wassail/wassail__Convertop.cmx"
  "_build/install/default/lib/wassail/wassail__Data_segment.cmi"
  "_build/install/default/lib/wassail/wassail__Data_segment.cmt"
  "_build/install/default/lib/wassail/wassail__Data_segment.cmx"
  "_build/install/default/lib/wassail/wassail__Dominance.cmi"
  "_build/install/default/lib/wassail/wassail__Dominance.cmt"
  "_build/install/default/lib/wassail/wassail__Dominance.cmx"
  "_build/install/default/lib/wassail/wassail__Elem_segment.cmi"
  "_build/install/default/lib/wassail/wassail__Elem_segment.cmt"
  "_build/install/default/lib/wassail/wassail__Elem_segment.cmx"
  "_build/install/default/lib/wassail/wassail__Export.cmi"
  "_build/install/default/lib/wassail/wassail__Export.cmt"
  "_build/install/default/lib/wassail/wassail__Export.cmx"
  "_build/install/default/lib/wassail/wassail__Func.cmi"
  "_build/install/default/lib/wassail/wassail__Func.cmt"
  "_build/install/default/lib/wassail/wassail__Func.cmx"
  "_build/install/default/lib/wassail/wassail__Func_inst.cmi"
  "_build/install/default/lib/wassail/wassail__Func_inst.cmt"
  "_build/install/default/lib/wassail/wassail__Func_inst.cmx"
  "_build/install/default/lib/wassail/wassail__Global.cmi"
  "_build/install/default/lib/wassail/wassail__Global.cmt"
  "_build/install/default/lib/wassail/wassail__Global.cmx"
  "_build/install/default/lib/wassail/wassail__Helpers.cmi"
  "_build/install/default/lib/wassail/wassail__Helpers.cmt"
  "_build/install/default/lib/wassail/wassail__Helpers.cmx"
  "_build/install/default/lib/wassail/wassail__Import.cmi"
  "_build/install/default/lib/wassail/wassail__Import.cmt"
  "_build/install/default/lib/wassail/wassail__Import.cmx"
  "_build/install/default/lib/wassail/wassail__Instr.cmi"
  "_build/install/default/lib/wassail/wassail__Instr.cmt"
  "_build/install/default/lib/wassail/wassail__Instr.cmx"
  "_build/install/default/lib/wassail/wassail__Instruction_counter.cmi"
  "_build/install/default/lib/wassail/wassail__Instruction_counter.cmt"
  "_build/install/default/lib/wassail/wassail__Instruction_counter.cmx"
  "_build/install/default/lib/wassail/wassail__Inter.cmi"
  "_build/install/default/lib/wassail/wassail__Inter.cmt"
  "_build/install/default/lib/wassail/wassail__Inter.cmx"
  "_build/install/default/lib/wassail/wassail__Intra.cmi"
  "_build/install/default/lib/wassail/wassail__Intra.cmt"
  "_build/install/default/lib/wassail/wassail__Intra.cmx"
  "_build/install/default/lib/wassail/wassail__Lexical_successor_tree.cmi"
  "_build/install/default/lib/wassail/wassail__Lexical_successor_tree.cmt"
  "_build/install/default/lib/wassail/wassail__Lexical_successor_tree.cmx"
  "_build/install/default/lib/wassail/wassail__Limits.cmi"
  "_build/install/default/lib/wassail/wassail__Limits.cmt"
  "_build/install/default/lib/wassail/wassail__Limits.cmx"
  "_build/install/default/lib/wassail/wassail__Log.cmi"
  "_build/install/default/lib/wassail/wassail__Log.cmt"
  "_build/install/default/lib/wassail/wassail__Log.cmx"
  "_build/install/default/lib/wassail/wassail__Memory.cmi"
  "_build/install/default/lib/wassail/wassail__Memory.cmt"
  "_build/install/default/lib/wassail/wassail__Memory.cmx"
  "_build/install/default/lib/wassail/wassail__Memory_deps.cmi"
  "_build/install/default/lib/wassail/wassail__Memory_deps.cmt"
  "_build/install/default/lib/wassail/wassail__Memory_deps.cmx"
  "_build/install/default/lib/wassail/wassail__Memory_inst.cmi"
  "_build/install/default/lib/wassail/wassail__Memory_inst.cmt"
  "_build/install/default/lib/wassail/wassail__Memory_inst.cmx"
  "_build/install/default/lib/wassail/wassail__Memoryop.cmi"
  "_build/install/default/lib/wassail/wassail__Memoryop.cmt"
  "_build/install/default/lib/wassail/wassail__Memoryop.cmx"
  "_build/install/default/lib/wassail/wassail__Module_inst.cmi"
  "_build/install/default/lib/wassail/wassail__Module_inst.cmt"
  "_build/install/default/lib/wassail/wassail__Module_inst.cmx"
  "_build/install/default/lib/wassail/wassail__Prim_value.cmi"
  "_build/install/default/lib/wassail/wassail__Prim_value.cmt"
  "_build/install/default/lib/wassail/wassail__Prim_value.cmx"
  "_build/install/default/lib/wassail/wassail__Ref_type.cmi"
  "_build/install/default/lib/wassail/wassail__Ref_type.cmt"
  "_build/install/default/lib/wassail/wassail__Ref_type.cmx"
  "_build/install/default/lib/wassail/wassail__Relop.cmi"
  "_build/install/default/lib/wassail/wassail__Relop.cmt"
  "_build/install/default/lib/wassail/wassail__Relop.cmx"
  "_build/install/default/lib/wassail/wassail__Rule_parser.cmi"
  "_build/install/default/lib/wassail/wassail__Rule_parser.cmt"
  "_build/install/default/lib/wassail/wassail__Rule_parser.cmx"
  "_build/install/default/lib/wassail/wassail__Segment.cmi"
  "_build/install/default/lib/wassail/wassail__Segment.cmt"
  "_build/install/default/lib/wassail/wassail__Segment.cmx"
  "_build/install/default/lib/wassail/wassail__Segment_mode.cmi"
  "_build/install/default/lib/wassail/wassail__Segment_mode.cmt"
  "_build/install/default/lib/wassail/wassail__Segment_mode.cmx"
  "_build/install/default/lib/wassail/wassail__Sizes.cmi"
  "_build/install/default/lib/wassail/wassail__Sizes.cmt"
  "_build/install/default/lib/wassail/wassail__Sizes.cmx"
  "_build/install/default/lib/wassail/wassail__Slicing.cmi"
  "_build/install/default/lib/wassail/wassail__Slicing.cmt"
  "_build/install/default/lib/wassail/wassail__Slicing.cmx"
  "_build/install/default/lib/wassail/wassail__Spec.cmi"
  "_build/install/default/lib/wassail/wassail__Spec.cmt"
  "_build/install/default/lib/wassail/wassail__Spec.cmx"
  "_build/install/default/lib/wassail/wassail__Spec_analysis.cmi"
  "_build/install/default/lib/wassail/wassail__Spec_analysis.cmt"
  "_build/install/default/lib/wassail/wassail__Spec_analysis.cmx"
  "_build/install/default/lib/wassail/wassail__Spec_inference.cmi"
  "_build/install/default/lib/wassail/wassail__Spec_inference.cmt"
  "_build/install/default/lib/wassail/wassail__Spec_inference.cmx"
  "_build/install/default/lib/wassail/wassail__Table.cmi"
  "_build/install/default/lib/wassail/wassail__Table.cmt"
  "_build/install/default/lib/wassail/wassail__Table.cmx"
  "_build/install/default/lib/wassail/wassail__Table_inst.cmi"
  "_build/install/default/lib/wassail/wassail__Table_inst.cmt"
  "_build/install/default/lib/wassail/wassail__Table_inst.cmx"
  "_build/install/default/lib/wassail/wassail__Taint.cmi"
  "_build/install/default/lib/wassail/wassail__Taint.cmt"
  "_build/install/default/lib/wassail/wassail__Taint.cmx"
  "_build/install/default/lib/wassail/wassail__Taint_domain.cmi"
  "_build/install/default/lib/wassail/wassail__Taint_domain.cmt"
  "_build/install/default/lib/wassail/wassail__Taint_domain.cmx"
  "_build/install/default/lib/wassail/wassail__Taint_options.cmi"
  "_build/install/default/lib/wassail/wassail__Taint_options.cmt"
  "_build/install/default/lib/wassail/wassail__Taint_options.cmx"
  "_build/install/default/lib/wassail/wassail__Taint_summary.cmi"
  "_build/install/default/lib/wassail/wassail__Taint_summary.cmt"
  "_build/install/default/lib/wassail/wassail__Taint_summary.cmx"
  "_build/install/default/lib/wassail/wassail__Taint_transfer.cmi"
  "_build/install/default/lib/wassail/wassail__Taint_transfer.cmt"
  "_build/install/default/lib/wassail/wassail__Taint_transfer.cmx"
  "_build/install/default/lib/wassail/wassail__Taintcall.cmi"
  "_build/install/default/lib/wassail/wassail__Taintcall.cmt"
  "_build/install/default/lib/wassail/wassail__Taintcall.cmx"
  "_build/install/default/lib/wassail/wassail__Taintcall_domain.cmi"
  "_build/install/default/lib/wassail/wassail__Taintcall_domain.cmt"
  "_build/install/default/lib/wassail/wassail__Taintcall_domain.cmx"
  "_build/install/default/lib/wassail/wassail__Taintcall_transfer.cmi"
  "_build/install/default/lib/wassail/wassail__Taintcall_transfer.cmt"
  "_build/install/default/lib/wassail/wassail__Taintcall_transfer.cmx"
  "_build/install/default/lib/wassail/wassail__Test.cmi"
  "_build/install/default/lib/wassail/wassail__Test.cmt"
  "_build/install/default/lib/wassail/wassail__Test.cmx"
  "_build/install/default/lib/wassail/wassail__Testop.cmi"
  "_build/install/default/lib/wassail/wassail__Testop.cmt"
  "_build/install/default/lib/wassail/wassail__Testop.cmx"
  "_build/install/default/lib/wassail/wassail__Transfer.cmi"
  "_build/install/default/lib/wassail/wassail__Transfer.cmt"
  "_build/install/default/lib/wassail/wassail__Transfer.cmx"
  "_build/install/default/lib/wassail/wassail__Tree.cmi"
  "_build/install/default/lib/wassail/wassail__Tree.cmt"
  "_build/install/default/lib/wassail/wassail__Tree.cmx"
  "_build/install/default/lib/wassail/wassail__Type.cmi"
  "_build/install/default/lib/wassail/wassail__Type.cmt"
  "_build/install/default/lib/wassail/wassail__Type.cmx"
  "_build/install/default/lib/wassail/wassail__Unop.cmi"
  "_build/install/default/lib/wassail/wassail__Unop.cmt"
  "_build/install/default/lib/wassail/wassail__Unop.cmx"
  "_build/install/default/lib/wassail/wassail__Unsupported.cmi"
  "_build/install/default/lib/wassail/wassail__Unsupported.cmt"
  "_build/install/default/lib/wassail/wassail__Unsupported.cmx"
  "_build/install/default/lib/wassail/wassail__Use_def.cmi"
  "_build/install/default/lib/wassail/wassail__Use_def.cmt"
  "_build/install/default/lib/wassail/wassail__Use_def.cmx"
  "_build/install/default/lib/wassail/wassail__Var.cmi"
  "_build/install/default/lib/wassail/wassail__Var.cmt"
  "_build/install/default/lib/wassail/wassail__Var.cmx"
  "_build/install/default/lib/wassail/wassail__Var_prop.cmi"
  "_build/install/default/lib/wassail/wassail__Var_prop.cmt"
  "_build/install/default/lib/wassail/wassail__Var_prop.cmx"
  "_build/install/default/lib/wassail/wassail__Wasm_helpers.cmi"
  "_build/install/default/lib/wassail/wassail__Wasm_helpers.cmt"
  "_build/install/default/lib/wassail/wassail__Wasm_helpers.cmx"
  "_build/install/default/lib/wassail/wassail__Wasm_module.cmi"
  "_build/install/default/lib/wassail/wassail__Wasm_module.cmt"
  "_build/install/default/lib/wassail/wassail__Wasm_module.cmx"
]
libexec: [
  "_build/install/default/lib/wassail/wassail.cmxs"
]
bin: [
  "_build/install/default/bin/wassail"
]
doc: [
  "_build/install/default/doc/wassail/LICENSE"
  "_build/install/default/doc/wassail/README.md"
]
